services:
  - type: web
    name: signalplushealthlandingpage
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PWA_ORIGIN
        sync: false
