services:
  - type: web
    name: signalplushealthlandingpage
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: RESEND_API_KEY
        sync: false
      - key: RESEND_NEWSLETTER_SEGMENT_ID
        sync: false
